# Streaming Music Data (from Spotify and YouTube)

This dataset has a *lot* more rows and columns of data than the previous examples, so we'll need to carefully explore the data first, then determine which parts of the data are the most important or interesting, and then we'll know which kinds of data visualizations we should use.

In [ ]:
# load libraries
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import squarify

In [ ]:
# import data
filePath = os.path.join('.','data','music.csv')
df = pd.read_csv(filePath)

In [11]:
# Standard data exploration techniques

# Size and shape of data
print('Size: ', df.size, '\tShape: ', df.shape, '\n')

# Dataframe info
df.info()

Size:  580104 	Shape:  (20718, 28)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20718 entries, 0 to 20717
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        20718 non-null  int64
 1   Artist            20718 non-null  object
 2   Url_spotify       20718 non-null  object
 3   Track             20718 non-null  object
 4   Album             20718 non-null  object
 5   Album_type        20718 non-null  object
 6   Uri               20718 non-null  object
 7   Danceability      20716 non-null  float64
 8   Energy            20716 non-null  float64
 9   Key               20716 non-null  float64
 10  Loudness          20716 non-null  float64
 11  Speechiness       20716 non-null  float64
 12  Acousticness      20716 non-null  float64
 13  Instrumentalness  20716 non-null  float64
 14  Liveness          20716 non-null  float64
 15  Valence           20716 non-null  float64
 16  Tempo             20716 non-null  float64
 17  Duration_ms       20716 non-null  float64
 18  Url_youtube       20248 non-null  object
 19  Title             20248 non-null  object
 20  Channel           20248 non-null  object
 21  Views             20248 non-null  float64
 22  Likes             20177 non-null  float64
 23  Comments          20149 non-null  float64
 24  Description       19842 non-null  object
 25  Licensed          20248 non-null  object
 26  official_video    20248 non-null  object
 27  Stream            20142 non-null  float64
dtypes: float64(15), int64(1), object(12)
memory usage: 4.4+ MB

In [12]:
# Deeper data exploration techniques

# Describe the contents of the dataframe
df.describe()

,Unnamed: 0,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Views,Likes,Comments,Stream
count,20718.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,2.071600e+04,2.024800e+04,2.017700e+04,2.014900e+04,2.014200e+04
mean,10358.500000,0.619777,0.635250,5.300348,-7.671680,0.096456,0.291535,0.055962,0.193521,0.529853,120.638340,2.247176e+05,9.393782e+07,6.633411e+05,2.751899e+04,1.359422e+08
std,5980.915774,0.165272,0.214147,3.576449,4.632749,0.111960,0.286299,0.193262,0.168531,0.245441,29.579018,1.247905e+05,2.746443e+08,1.789324e+06,1.932347e+05,2.441321e+08
min,0.000000,0.000000,0.000020,0.000000,-46.251000,0.000000,0.000001,0.000000,0.014500,0.000000,0.000000,3.098500e+04,0.000000e+00,0.000000e+00,0.000000e+00,6.574000e+03
25%,5179.250000,0.518000,0.507000,2.000000,-8.858000,0.035700,0.045200,0.000000,0.094100,0.339000,97.002000,1.800095e+05,1.826002e+06,2.158100e+04,5.090000e+02,1.767486e+07
50%,10358.500000,0.637000,0.666000,5.000000,-6.536000,0.050500,0.193000,0.000002,0.125000,0.537000,119.965000,2.132845e+05,1.450110e+07,1.244810e+05,3.277000e+03,4.968298e+07
75%,15537.750000,0.740250,0.798000,8.000000,-4.931000,0.103000,0.477250,0.000463,0.237000,0.726250,139.935000,2.524430e+05,7.039975e+07,5.221480e+05,1.436000e+04,1.383581e+08
max,20717.000000,0.975000,1.000000,11.000000,0.920000,0.964000,0.996000,1.000000,1.000000,0.993000,243.372000,4.676058e+06,8.079649e+09,5.078865e+07,1.608314e+07,3.386520e+09

In [ ]:
# Top 10 songs by Likes (sum the Likes column and group by Artist)

In [ ]:
# 10 longest songs and 10 shortest songs (use the Duration_ms column)

In [ ]:
# Top 10 songs by play count (add the Views + Streams columns together)

In [ ]:
# Top 10 artists by play count (add the Views + Streams columns together, then sum that result and group by Artist)